export { default as DashboardIcon } from './dashboard.svg'
export { default as AssessmentIcon } from './assessment.svg'
export { default as LibraryIcon } from './library.svg'
export { default as RoundStatusIcon } from './roundstatus.svg'
export { default as MenuIcon } from './menu.svg'
