//ICONS 
export { default as DashboardIcon } from './icons/dashboard.svg'
export { default as AssessmentIcon } from './icons/assessment.svg'
export { default as LibraryIcon } from './icons/library.svg'
export { default as RoundStatusIcon } from './icons/roundstatus.svg'
export { default as MenuIcon } from './icons/menu.svg'
export { default as CloseIcon } from './icons/close.svg'
export { default as TotalAssessIcon } from './icons/totalAssess.svg'
export { default as CandidateIcon } from './icons/candidates.svg'
export { default as CandidateEmailIcon } from './icons/candidateEmail.svg'
export { default as LinkIcon } from './icons/link.svg'
export { default as PlusIcon } from './icons/plus.svg'
export { default as OptionsIcon } from './icons/options.svg'
export { default as AssessIcon } from './icons/assess.svg'
export { default as CalendarIcon } from './icons/calendar.svg'
export { default as UrlIcon } from './icons/url.svg'
export { default as SearchIcon } from './icons/search.svg'
export { default as FunnelIcon } from './icons/funnel.svg'
export { default as AnalyticsIcon } from './icons/analytics.svg'
export {default as ClockIcon} from './icons/clock.svg'
export { default as CloseRedIcon } from './icons/closeRed.svg'
